### ISSUE TITLE
Running Flowket under CPU parallelization with MPI

### ISSUE THREAD

**Issue by NnktYoshioka** [HUJI-Deep/FlowKet#18]
Hi, 

Walking through the examples such as [this code](http://localhost:8888/edit/0_flowket/FlowKet-master/examples/heisenberg_2d_horvod_multy_gpu_fast_sampling.py), I noticed that we can speed up the sampling by using GPUs.
I am not an expert of tensorflow or Horovod, but from the [website of Horovod](https://horovod.readthedocs.io/en/stable/install_include.html) I understand that it is capable of calculation using MPI.

May I ask if it is possible to run flowket codes without GPU but with CPU parallelization using MPI?
If so, how shall I modify the codes?
(I do not have GPU machines right now, so wanted to know if my current environment in supercomputers are fine)

Thank you very much for your help in advance.

Best regards,
Nobu

**Comment by noamwies** [comment]
The example name "heisenberg_2d_horvod_multy_gpu_fast_sampling.py" is slightly misleading, actually the parallelism is  for the entire training steps (and not only the sampling).

I never tried to run Flowket on CPU clusters but from [here ](https://github.com/horovod/horovod/issues/987)it seem that it's possible.

Regarding the example, please look at the updated version that average the energy over the MPI cluster, if you plan to use
```StochasticReconfiguration```  you should add similar logic to ```ComplexValuesStochasticReconfiguration```
