### ISSUE TITLE
Cannot pip install flowket!

### ISSUE THREAD

**Issue by XiaoTailong** [HUJI-Deep/FlowKet#19]
When I use the command pip install flowket, the terminal will always remind me the HTTPerrors. I believe my network is work well. I doubt the package is wether properly well released.

**Comment by noamwies** [comment]
@XiaoTailong
Does manually downloading [flowket-0.2.2-py3-none-any.whl ](https://files.pythonhosted.org/packages/22/67/6ca57a9bda978e17e45adc369310554a8b60a108c8452af8ad2c822c9198/flowket-0.2.2-py3-none-any.whl)  solve the problem ?
Noam

**Comment by XiaoTailong** [comment]
> @XiaoTailong
> Does manually downloading [flowket-0.2.2-py3-none-any.whl ](https://files.pythonhosted.org/packages/22/67/6ca57a9bda978e17e45adc369310554a8b60a108c8452af8ad2c822c9198/flowket-0.2.2-py3-none-any.whl) solve the problem ?
> Noam

Thanks! I have successfully installed the package.
