### ISSUE TITLE
module named error

### ISSUE THREAD

**Issue by XiaoTailong** [HUJI-Deep/FlowKet#20]
Traceback (most recent call last):
  File "basic_autoregressive_2d.py", line 10, in <module>
    from flowket.optimization import VariationalMonteCarlo, loss_for_energy_minimization
  File "/home/---/.conda/envs/pytorch-gpu/lib/python3.7/site-packages/flowket/optimization/__init__.py", line 3, in <module>
    from .exact_variational import ExactVariational
  File "/home/---/.conda/envs/pytorch-gpu/lib/python3.7/site-packages/flowket/optimization/exact_variational.py", line 3, in <module>
    from ..exact.utils import binary_array_to_decimal_array, decimal_array_to_binary_array, fsum, complex_norm_log_fsum_exp
ModuleNotFoundError: No module named 'flowket.exact'

When I run the files in experiment folder, I always meet the above error. I am sure my package is well installed.

**Comment by noamwies** [comment]
@XiaoTailong 
Thanks,  I fixed the issue and updated the pypi package, please update to the new package and let me know if it works.

**Comment by XiaoTailong** [comment]
> @XiaoTailong
> Thanks, I fixed the issue and updated the pypi package, please update to the new package and let me know if it works.

I installed the new package. The above error was solved. But when I run Ising_test.py file, I still encounter a new error.

Traceback (most recent call last):
  File "Ising_test.py", line 169, in <module>
    run(params, batch_size_list, epochs_list)
  File "Ising_test.py", line 92, in run
    true_ground_state_energy = true_ground_state_energy_mapping[params.gamma]
KeyError: None

**Comment by noamwies** [comment]
@XiaoTailong
Did you mean ```examples/ising.py``` file?
You should run it with a gamma argument  e.g. ```python3 ising.py --gamma 2.0```.
Moreover it just an example of the API usage, if you want to obtain SOTA results the ```experiments``` folder can be a good starting point (run with --help to see the required argument).

**Comment by XiaoTailong** [comment]
> @XiaoTailong
> Did you mean `examples/ising.py` file?
> You should run it with a gamma argument e.g. `python3 ising.py --gamma 2.0`.
> Moreover it just an example of the API usage, if you want to obtain SOTA results the `experiments` folder can be a good starting point (run with --help to see the required argument).

Thanks, I will give it a try!

**Comment by XiaoTailong** [comment]
Hello! I have run the experiments of Ising.py. The file aims to obtain the ground energy of the Ising model. I wonder if i can use the model to obtain the ground state corresponding to the ground energy. I believe the model is able to output ground state but I have no idea how to achieve it. Can you give me some guidelines?

**Comment by noamwies** [comment]
@XiaoTailong 

If your's hilbert space is small enough you can use ```to_log_wave_function_vector``` to get the explicit full (log) wave function.
```python
import numpy as np
import tensorflow
from flowket.machines import ConvNetAutoregressive2D
from flowket.exact.utils import to_log_wave_function_vector, decimal_array_to_binary_array

input_size = (4, 4)
inputs = tensorflow.keras.layers.Input(shape=input_size, dtype='int8')
convnet = ConvNetAutoregressive2D(inputs, ...)
model = tensorflow.keras.models.Model(inputs=inputs, outputs=convnet.predictions)
model.load_weights("pre-trained weights path")
log_wave_function = to_log_wave_function_vector(model)

# below you can construct the coresponding state for each enrty in the wave function
number_of_spins = np.prod(input_size)
num_of_states = 2 ** number_of_spins
states = decimal_array_to_binary_array(np.arange(num_of_states), number_of_spins, False).reshape((num_of_states, ) + input_size)

```

Otherwise you can still get specific entries of the (normalaized) wave function by 

```python
num_of_states = 2
states = np.array((num_of_states,)+input_size, dtype=np.int32)
states[0, ...] = np.array([[1, 1, -1, -1], [1, 1, -1, -1], [1, 1, -1, -1], [1, 1, -1, -1]])
states[1, ...] = np.array([[1, 1, -1, -1], [1, -1, 1, -1], [1, -1, 1, -1], [1, 1, -1, -1]])
log_wave_function = model.predict(states)[:, 0]
```

And sample from the Born probabilty by ```FastAutoregressiveSampler```
```python
from flowket.samplers import FastAutoregressiveSampler

sampler = FastAutoregressiveSampler(tensorflow.keras.models.Model(inputs=inputs, outputs=convnet.conditional_log_probs), 2**10)
sample = next(sampler)
```

You may also use ```flowket.evaluation.evaluate``` to estimate some operator
```python
from flowket.optimization import VariationalMonteCarlo
from flowket.callbacks.monte_carlo import default_wave_function_stats_callbacks_factory
from flowket.evaluation import evaluate
from flowket.operators import Ising
from flowket.observables.monte_carlo import Observable
from flowket.callbacks.monte_carlo improt ObservableStats

generator = VariationalMonteCarlo(model, Ising(input_size, pbc=False, h=2.), sampler, mini_batch_size=2**7)
callbacks = default_wave_function_stats_callbacks_factory(generator, log_in_batch_or_epoch=False)
operator = ... # implements flowket.operators.Operator
callbacks += [ObservableStats(generator, Observable(operator), 'operator_name', log_in_batch_or_epoch=False)]
evaluate(generator, steps, callbacks)
```

Finally, note that in all of the above examples you might want to make the wave function invariant to some symetries by adding the following lines (the Born sampling remain unchanged)

```python
from flowket.machines.ensemble import make_2d_obc_invariants, make_up_down_invariant

evaluation_inputs = Input(shape=input_size, dtype='int8')
obc_input = Input(shape=input_size, dtype='int8'))
model = make_2d_obc_invariants(obc_input, model)
model = make_up_down_invariant(evaluation_inputs, model)
```

**Comment by XiaoTailong** [comment]
Thank you very much!

**Comment by XiaoTailong** [comment]
> @XiaoTailong
> 
> If your's hilbert space is small enough you can use `to_log_wave_function_vector` to get the explicit full (log) wave function.
> 
> ```python
> import numpy as np
> import tensorflow
> from flowket.machines import ConvNetAutoregressive2D
> from flowket.exact.utils import to_log_wave_function_vector, decimal_array_to_binary_array
> 
> input_size = (4, 4)
> inputs = tensorflow.keras.layers.Input(shape=input_size, dtype='int8')
> convnet = ConvNetAutoregressive2D(inputs, ...)
> model = tensorflow.keras.models.Model(inputs=inputs, outputs=convnet.predictions)
> model.load_weights("pre-trained weights path")
> log_wave_function = to_log_wave_function_vector(model)
> 
> # below you can construct the coresponding state for each enrty in the wave function
> number_of_spins = np.prod(input_size)
> num_of_states = 2 ** number_of_spins
> states = decimal_array_to_binary_array(np.arange(num_of_states), number_of_spins, False).reshape((num_of_states, ) + input_size)
> ```
> 
> Otherwise you can still get specific entries of the (normalaized) wave function by
> 
> ```python
> num_of_states = 2
> states = np.array((num_of_states,)+input_size, dtype=np.int32)
> states[0, ...] = np.array([[1, 1, -1, -1], [1, 1, -1, -1], [1, 1, -1, -1], [1, 1, -1, -1]])
> states[1, ...] = np.array([[1, 1, -1, -1], [1, -1, 1, -1], [1, -1, 1, -1], [1, 1, -1, -1]])
> log_wave_function = model.predict(states)[:, 0]
> ```
> 
> And sample from the Born probabilty by `FastAutoregressiveSampler`
> 
> ```python
> from flowket.samplers import FastAutoregressiveSampler
> 
> sampler = FastAutoregressiveSampler(tensorflow.keras.models.Model(inputs=inputs, outputs=convnet.conditional_log_probs), 2**10)
> sample = next(sampler)
> ```
> 
> You may also use `flowket.evaluation.evaluate` to estimate some operator
> 
> ```python
> from flowket.optimization import VariationalMonteCarlo
> from flowket.callbacks.monte_carlo import default_wave_function_stats_callbacks_factory
> from flowket.evaluation import evaluate
> from flowket.operators import Ising
> from flowket.observables.monte_carlo import Observable
> from flowket.callbacks.monte_carlo improt ObservableStats
> 
> generator = VariationalMonteCarlo(model, Ising(input_size, pbc=False, h=2.), sampler, mini_batch_size=2**7)
> callbacks = default_wave_function_stats_callbacks_factory(generator, log_in_batch_or_epoch=False)
> operator = ... # implements flowket.operators.Operator
> callbacks += [ObservableStats(generator, Observable(operator), 'operator_name', log_in_batch_or_epoch=False)]
> evaluate(generator, steps, callbacks)
> ```
> 
> Finally, note that in all of the above examples you might want to make the wave function invariant to some symetries by adding the following lines (the Born sampling remain unchanged)
> 
> ```python
> from flowket.machines.ensemble import make_2d_obc_invariants, make_up_down_invariant
> 
> evaluation_inputs = Input(shape=input_size, dtype='int8')
> obc_input = Input(shape=input_size, dtype='int8'))
> model = make_2d_obc_invariants(obc_input, model)
> model = make_up_down_invariant(evaluation_inputs, model)
> ```

Thank you very much!

**Comment by XiaoTailong** [comment]
@noamwies 
Now I know how to get the explict form of ground state wavefunction for small model. For large model, I think the above method is not possible or avaliable. If I understood right, I could only obtain the obervables's expectation value from sampling the ground state waveefunction in large models. If I want to get measurement results, could I regard the measurement operators as the observables? Then I will obtain the samples of measurments just as examples done in netket package. 

Symetries, as i expected, can increase the precision of estimation. But I am not very clear how symetries exactly means for the estimation of ground state wavefunction? Or how do symetries mean to maching learning model? I may not very clear this physical concept.

**Comment by noamwies** [comment]
@XiaoTailong 
Sure, if you want to measurement  netket operator you can wrap it with ```NetketOperatorWrapper``` and pass the results as the observable

```python
from flowket.optimization import VariationalMonteCarlo
from flowket.callbacks.monte_carlo import default_wave_function_stats_callbacks_factory
from flowket.evaluation import evaluate
from flowket.operators import Ising, NetketOperatorWrapper
from flowket.observables.monte_carlo import Observable
from flowket.callbacks.monte_carlo improt ObservableStats

generator = VariationalMonteCarlo(model, Ising(input_size, pbc=False, h=2.), sampler, mini_batch_size=2**7)
callbacks = default_wave_function_stats_callbacks_factory(generator, log_in_batch_or_epoch=False)
netket_operator = ...
operator = NetketOperatorWrapper(netket_operator, input_size)
callbacks += [ObservableStats(generator, Observable(operator), 'operator_name', log_in_batch_or_epoch=False)]
evaluate(generator, steps, callbacks)
```

Regarding the symmetries, i just saying that empirically the ```make_2d_obc_invariants, make_up_down_invariant``` gives you wave function that is closer to the ground state.
I guess you can think of this as ensemble method , which is quiet common in machine learning
